"""operating authority detail and history

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 16:14:29.356321
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authority_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "docket_prefix",
            sa.Enum(
                "MC",
                "MX",
                "FF",
                name="docket_prefix",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("docket_number", sa.String(length=20), nullable=False),
        sa.Column("authority_type", sa.String(length=150), nullable=True),
        sa.Column("event_kind", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("action_date", sa.Date(), nullable=True),
        sa.Column("source_system", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_authority_history_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_authority_history_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authority_history")),
        sa.UniqueConstraint("raw_record_id", "event_kind", name="uq_authority_history_raw_kind"),
    )
    op.create_index(
        "ix_authority_history_carrier_date",
        "authority_history",
        ["carrier_id", "action_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authority_history_raw_record_id"),
        "authority_history",
        ["raw_record_id"],
        unique=False,
    )
    op.add_column("authority", sa.Column("status_source", sa.String(length=20), nullable=True))
    op.add_column("authority", sa.Column("status_as_of", sa.Date(), nullable=True))
    op.add_column(
        "authority", sa.Column("bipd_required", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "authority", sa.Column("bipd_on_file", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column("authority", sa.Column("cargo_required", sa.Boolean(), nullable=True))
    op.add_column("authority", sa.Column("cargo_on_file", sa.Boolean(), nullable=True))
    op.add_column("authority", sa.Column("bond_required", sa.Boolean(), nullable=True))
    op.add_column("authority", sa.Column("bond_on_file", sa.Boolean(), nullable=True))
    op.add_column("authority", sa.Column("revocation_pending", sa.Boolean(), nullable=True))
    op.alter_column(
        "authority",
        "authority_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "authority",
        "authority_type",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("authority", "revocation_pending")
    op.drop_column("authority", "bond_on_file")
    op.drop_column("authority", "bond_required")
    op.drop_column("authority", "cargo_on_file")
    op.drop_column("authority", "cargo_required")
    op.drop_column("authority", "bipd_on_file")
    op.drop_column("authority", "bipd_required")
    op.drop_column("authority", "status_as_of")
    op.drop_column("authority", "status_source")
    op.drop_index(op.f("ix_authority_history_raw_record_id"), table_name="authority_history")
    op.drop_index("ix_authority_history_carrier_date", table_name="authority_history")
    op.drop_table("authority_history")
    # ### end Alembic commands ###
