"""timeline event key

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 16:34:23.313459
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("timeline_events", sa.Column("event_key", sa.String(length=200), nullable=True))
    op.create_unique_constraint(
        "uq_timeline_events_carrier_key", "timeline_events", ["carrier_id", "event_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_timeline_events_carrier_key", "timeline_events", type_="unique")
    op.drop_column("timeline_events", "event_key")
    # ### end Alembic commands ###
