"""insurance filing detail

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 16:27:02.692378
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insurance",
        sa.Column(
            "docket_prefix",
            sa.Enum(
                "MC",
                "MX",
                "FF",
                name="docket_prefix",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column("insurance", sa.Column("docket_number", sa.String(length=20), nullable=True))
    op.add_column("insurance", sa.Column("insurance_class", sa.String(length=10), nullable=True))
    op.add_column("insurance", sa.Column("form_code", sa.String(length=10), nullable=True))
    op.add_column(
        "insurance", sa.Column("underlying_limit", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column(
        "insurance", sa.Column("on_file", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("insurance", sa.Column("received_date", sa.Date(), nullable=True))
    op.add_column("insurance", sa.Column("source_system", sa.String(length=20), nullable=True))
    op.add_column("insurance", sa.Column("status_as_of", sa.Date(), nullable=True))
    op.create_index(
        "ix_insurance_carrier_docket", "insurance", ["carrier_id", "docket_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_insurance_carrier_docket", table_name="insurance")
    op.drop_column("insurance", "status_as_of")
    op.drop_column("insurance", "source_system")
    op.drop_column("insurance", "received_date")
    op.drop_column("insurance", "on_file")
    op.drop_column("insurance", "underlying_limit")
    op.drop_column("insurance", "form_code")
    op.drop_column("insurance", "insurance_class")
    op.drop_column("insurance", "docket_number")
    op.drop_column("insurance", "docket_prefix")
    # ### end Alembic commands ###
