"""carrier data model

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 13:52:52.249902
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carriers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("usdot_number", sa.BigInteger(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("dba_name", sa.String(length=255), nullable=True),
        sa.Column("entity_type", sa.String(length=10), nullable=True),
        sa.Column("registration_status", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("fleet_size", sa.Integer(), nullable=True),
        sa.Column("driver_count", sa.Integer(), nullable=True),
        sa.Column("safety_rating", sa.String(length=20), nullable=True),
        sa.Column("safety_rating_date", sa.Date(), nullable=True),
        sa.Column("first_registered_date", sa.Date(), nullable=True),
        sa.Column("last_mcs150_date", sa.Date(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carriers")),
        sa.UniqueConstraint("usdot_number", name=op.f("uq_carriers_usdot_number")),
    )
    op.create_index(
        "ix_carriers_dba_name_trgm",
        "carriers",
        ["dba_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"dba_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_carriers_legal_name_trgm",
        "carriers",
        ["legal_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("dataset_id", sa.String(length=50), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="ingestion_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("records_fetched", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=False),
        sa.Column("decoded_make", sa.String(length=100), nullable=True),
        sa.Column("decoded_model", sa.String(length=100), nullable=True),
        sa.Column("decoded_year", sa.SmallInteger(), nullable=True),
        sa.Column("decoded_body_class", sa.String(length=100), nullable=True),
        sa.Column("decoded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("vin", name=op.f("uq_vehicles_vin")),
    )
    op.create_table(
        "identity_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("corrects_event_id", sa.BigInteger(), nullable=True),
        sa.Column("supporting_document", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="manual", nullable=False),
        sa.Column("entered_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_identity_events_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["corrects_event_id"],
            ["identity_events.id"],
            name=op.f("fk_identity_events_corrects_event_id_identity_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_events")),
    )
    op.create_index(
        op.f("ix_identity_events_carrier_id"), "identity_events", ["carrier_id"], unique=False
    )
    op.create_index(
        op.f("ix_identity_events_corrects_event_id"),
        "identity_events",
        ["corrects_event_id"],
        unique=False,
    )
    op.create_table(
        "intelligence_signals",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("rule_id", sa.String(length=50), nullable=False),
        sa.Column("rule_version", sa.String(length=20), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="severity",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH",
                "MEDIUM",
                "LOW",
                name="confidence",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "REVIEWED",
                "DISMISSED",
                name="signal_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_intelligence_signals_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intelligence_signals")),
    )
    op.create_index(
        op.f("ix_intelligence_signals_carrier_id"),
        "intelligence_signals",
        ["carrier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intelligence_signals_signal_type"),
        "intelligence_signals",
        ["signal_type"],
        unique=False,
    )
    op.create_table(
        "raw_records",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("dataset_id", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_raw_records_ingestion_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_records")),
    )
    op.create_index(
        op.f("ix_raw_records_ingestion_run_id"), "raw_records", ["ingestion_run_id"], unique=False
    )
    op.create_index(
        "ix_raw_records_source_key",
        "raw_records",
        ["source", "dataset_id", "external_id"],
        unique=False,
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "address_type",
            sa.Enum(
                "PHYSICAL",
                "MAILING",
                name="address_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip", sa.String(length=20), nullable=True),
        sa.Column("county_code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("undeliverable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_addresses_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_addresses_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(op.f("ix_addresses_carrier_id"), "addresses", ["carrier_id"], unique=False)
    op.create_index(
        op.f("ix_addresses_raw_record_id"), "addresses", ["raw_record_id"], unique=False
    )
    op.create_table(
        "authority",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "docket_prefix",
            sa.Enum(
                "MC",
                "MX",
                "FF",
                name="docket_prefix",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("docket_number", sa.String(length=20), nullable=False),
        sa.Column("authority_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("status_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_authority_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_authority_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authority")),
        sa.UniqueConstraint(
            "carrier_id", "docket_prefix", "docket_number", name="uq_authority_carrier_docket"
        ),
    )
    op.create_index(op.f("ix_authority_carrier_id"), "authority", ["carrier_id"], unique=False)
    op.create_index(
        op.f("ix_authority_docket_number"), "authority", ["docket_number"], unique=False
    )
    op.create_index(
        op.f("ix_authority_raw_record_id"), "authority", ["raw_record_id"], unique=False
    )
    op.create_table(
        "carrier_attribute_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_carrier_attribute_history_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_carrier_attribute_history_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_carrier_attribute_history_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_attribute_history")),
    )
    op.create_index(
        "ix_carrier_attribute_history_lookup",
        "carrier_attribute_history",
        ["carrier_id", "attribute", "valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carrier_attribute_history_raw_record_id"),
        "carrier_attribute_history",
        ["raw_record_id"],
        unique=False,
    )
    op.create_index(
        "uq_carrier_attribute_history_current",
        "carrier_attribute_history",
        ["carrier_id", "attribute"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "carrier_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("data_hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_carrier_snapshots_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_carrier_snapshots_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_snapshots")),
    )
    op.create_index(
        "ix_carrier_snapshots_carrier_date",
        "carrier_snapshots",
        ["carrier_id", "snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carrier_snapshots_raw_record_id"),
        "carrier_snapshots",
        ["raw_record_id"],
        unique=False,
    )
    op.create_table(
        "crashes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("crash_id", sa.String(length=50), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("crash_date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("fatalities", sa.Integer(), server_default="0", nullable=False),
        sa.Column("injuries", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tow_away", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_crashes_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"], ["raw_records.id"], name=op.f("fk_crashes_raw_record_id_raw_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crashes")),
        sa.UniqueConstraint("source", "crash_id", name="uq_crashes_source_crash_id"),
    )
    op.create_index(op.f("ix_crashes_carrier_id"), "crashes", ["carrier_id"], unique=False)
    op.create_index(op.f("ix_crashes_crash_date"), "crashes", ["crash_date"], unique=False)
    op.create_index(op.f("ix_crashes_raw_record_id"), "crashes", ["raw_record_id"], unique=False)
    op.create_index(op.f("ix_crashes_vin"), "crashes", ["vin"], unique=False)
    op.create_table(
        "domains",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column(
            "origin",
            sa.Enum(
                "EMAIL",
                "WEBSITE",
                name="domain_origin",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_domains_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"], ["raw_records.id"], name=op.f("fk_domains_raw_record_id_raw_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domains")),
    )
    op.create_index(op.f("ix_domains_carrier_id"), "domains", ["carrier_id"], unique=False)
    op.create_index(op.f("ix_domains_domain"), "domains", ["domain"], unique=False)
    op.create_index(op.f("ix_domains_raw_record_id"), "domains", ["raw_record_id"], unique=False)
    op.create_table(
        "inspections",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inspection_id", sa.String(length=50), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column("inspection_date", sa.Date(), nullable=False),
        sa.Column("inspection_level", sa.SmallInteger(), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("vehicle_oos", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("driver_oos", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("violation_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_inspections_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_inspections_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
        sa.UniqueConstraint("source", "inspection_id", name="uq_inspections_source_inspection_id"),
    )
    op.create_index(op.f("ix_inspections_carrier_id"), "inspections", ["carrier_id"], unique=False)
    op.create_index(
        op.f("ix_inspections_inspection_date"), "inspections", ["inspection_date"], unique=False
    )
    op.create_index(
        op.f("ix_inspections_raw_record_id"), "inspections", ["raw_record_id"], unique=False
    )
    op.create_index(op.f("ix_inspections_vin"), "inspections", ["vin"], unique=False)
    op.create_table(
        "insurance",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("insurer", sa.String(length=255), nullable=True),
        sa.Column("insurance_type", sa.String(length=50), nullable=True),
        sa.Column("coverage_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("termination_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_insurance_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_insurance_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance")),
    )
    op.create_index(op.f("ix_insurance_carrier_id"), "insurance", ["carrier_id"], unique=False)
    op.create_index(
        op.f("ix_insurance_raw_record_id"), "insurance", ["raw_record_id"], unique=False
    )
    op.create_table(
        "officers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_officers_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_officers_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_officers")),
    )
    op.create_index(op.f("ix_officers_carrier_id"), "officers", ["carrier_id"], unique=False)
    op.create_index(op.f("ix_officers_name"), "officers", ["name"], unique=False)
    op.create_index(op.f("ix_officers_raw_record_id"), "officers", ["raw_record_id"], unique=False)
    op.create_table(
        "phones",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "phone_type",
            sa.Enum(
                "OFFICE",
                "CELL",
                "FAX",
                name="phone_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("number_normalized", sa.String(length=20), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_phones_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"], ["raw_records.id"], name=op.f("fk_phones_raw_record_id_raw_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phones")),
    )
    op.create_index(op.f("ix_phones_carrier_id"), "phones", ["carrier_id"], unique=False)
    op.create_index(
        op.f("ix_phones_number_normalized"), "phones", ["number_normalized"], unique=False
    )
    op.create_index(op.f("ix_phones_raw_record_id"), "phones", ["raw_record_id"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_entity_type", sa.String(length=50), nullable=False),
        sa.Column("source_entity_id", sa.BigInteger(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("target_entity_type", sa.String(length=50), nullable=False),
        sa.Column("target_entity_id", sa.BigInteger(), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("observation_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH",
                "MEDIUM",
                "LOW",
                name="confidence",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_relationships_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint(
            "source_entity_type",
            "source_entity_id",
            "relationship_type",
            "target_entity_type",
            "target_entity_id",
            name="uq_relationships_link",
        ),
    )
    op.create_index(
        op.f("ix_relationships_raw_record_id"), "relationships", ["raw_record_id"], unique=False
    )
    op.create_index(
        "ix_relationships_target",
        "relationships",
        ["target_entity_type", "target_entity_id"],
        unique=False,
    )
    op.create_table(
        "signal_evidence",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column("field_name", sa.String(length=64), nullable=True),
        sa.Column("observed_value", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_signal_evidence_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["intelligence_signals.id"],
            name=op.f("fk_signal_evidence_signal_id_intelligence_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_evidence")),
    )
    op.create_index(
        op.f("ix_signal_evidence_raw_record_id"), "signal_evidence", ["raw_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_signal_evidence_signal_id"), "signal_evidence", ["signal_id"], unique=False
    )
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="severity",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_timeline_events_carrier_id_carriers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.id"],
            name=op.f("fk_timeline_events_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["intelligence_signals.id"],
            name=op.f("fk_timeline_events_signal_id_intelligence_signals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    op.create_index(
        "ix_timeline_events_carrier_date",
        "timeline_events",
        ["carrier_id", "event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timeline_events_raw_record_id"), "timeline_events", ["raw_record_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_signal_id"), "timeline_events", ["signal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeline_events_signal_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_raw_record_id"), table_name="timeline_events")
    op.drop_index("ix_timeline_events_carrier_date", table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_signal_evidence_signal_id"), table_name="signal_evidence")
    op.drop_index(op.f("ix_signal_evidence_raw_record_id"), table_name="signal_evidence")
    op.drop_table("signal_evidence")
    op.drop_index("ix_relationships_target", table_name="relationships")
    op.drop_index(op.f("ix_relationships_raw_record_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_phones_raw_record_id"), table_name="phones")
    op.drop_index(op.f("ix_phones_number_normalized"), table_name="phones")
    op.drop_index(op.f("ix_phones_carrier_id"), table_name="phones")
    op.drop_table("phones")
    op.drop_index(op.f("ix_officers_raw_record_id"), table_name="officers")
    op.drop_index(op.f("ix_officers_name"), table_name="officers")
    op.drop_index(op.f("ix_officers_carrier_id"), table_name="officers")
    op.drop_table("officers")
    op.drop_index(op.f("ix_insurance_raw_record_id"), table_name="insurance")
    op.drop_index(op.f("ix_insurance_carrier_id"), table_name="insurance")
    op.drop_table("insurance")
    op.drop_index(op.f("ix_inspections_vin"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_raw_record_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_inspection_date"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_carrier_id"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_domains_raw_record_id"), table_name="domains")
    op.drop_index(op.f("ix_domains_domain"), table_name="domains")
    op.drop_index(op.f("ix_domains_carrier_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_crashes_vin"), table_name="crashes")
    op.drop_index(op.f("ix_crashes_raw_record_id"), table_name="crashes")
    op.drop_index(op.f("ix_crashes_crash_date"), table_name="crashes")
    op.drop_index(op.f("ix_crashes_carrier_id"), table_name="crashes")
    op.drop_table("crashes")
    op.drop_index(op.f("ix_carrier_snapshots_raw_record_id"), table_name="carrier_snapshots")
    op.drop_index("ix_carrier_snapshots_carrier_date", table_name="carrier_snapshots")
    op.drop_table("carrier_snapshots")
    op.drop_index(
        "uq_carrier_attribute_history_current",
        table_name="carrier_attribute_history",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(
        op.f("ix_carrier_attribute_history_raw_record_id"), table_name="carrier_attribute_history"
    )
    op.drop_index("ix_carrier_attribute_history_lookup", table_name="carrier_attribute_history")
    op.drop_table("carrier_attribute_history")
    op.drop_index(op.f("ix_authority_raw_record_id"), table_name="authority")
    op.drop_index(op.f("ix_authority_docket_number"), table_name="authority")
    op.drop_index(op.f("ix_authority_carrier_id"), table_name="authority")
    op.drop_table("authority")
    op.drop_index(op.f("ix_addresses_raw_record_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_carrier_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index("ix_raw_records_source_key", table_name="raw_records")
    op.drop_index(op.f("ix_raw_records_ingestion_run_id"), table_name="raw_records")
    op.drop_table("raw_records")
    op.drop_index(op.f("ix_intelligence_signals_signal_type"), table_name="intelligence_signals")
    op.drop_index(op.f("ix_intelligence_signals_carrier_id"), table_name="intelligence_signals")
    op.drop_table("intelligence_signals")
    op.drop_index(op.f("ix_identity_events_corrects_event_id"), table_name="identity_events")
    op.drop_index(op.f("ix_identity_events_carrier_id"), table_name="identity_events")
    op.drop_table("identity_events")
    op.drop_table("vehicles")
    op.drop_table("ingestion_runs")
    op.drop_index(
        "ix_carriers_legal_name_trgm",
        table_name="carriers",
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_carriers_dba_name_trgm",
        table_name="carriers",
        postgresql_using="gin",
        postgresql_ops={"dba_name": "gin_trgm_ops"},
    )
    op.drop_table("carriers")
    # ### end Alembic commands ###
