"""carrier operation classification

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 16:56:41.681174
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carriers", sa.Column("operation_classification", sa.String(length=300), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("carriers", "operation_classification")
    # ### end Alembic commands ###
