"""vehicle decode detail

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 17:04:04.659493
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicles", sa.Column("decoded_vehicle_type", sa.String(length=100), nullable=True)
    )
    op.add_column("vehicles", sa.Column("decoded_gvwr", sa.String(length=100), nullable=True))
    op.add_column(
        "vehicles", sa.Column("decoded_manufacturer", sa.String(length=200), nullable=True)
    )
    op.add_column("vehicles", sa.Column("decode_error_code", sa.String(length=50), nullable=True))
    op.add_column("vehicles", sa.Column("decode_error_text", sa.Text(), nullable=True))
    op.add_column("vehicles", sa.Column("check_digit_valid", sa.Boolean(), nullable=True))
    op.add_column("vehicles", sa.Column("decode_raw_record_id", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_vehicles_decode_raw_record_id"), "vehicles", ["decode_raw_record_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_vehicles_decode_raw_record_id_raw_records"),
        "vehicles",
        "raw_records",
        ["decode_raw_record_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_vehicles_decode_raw_record_id_raw_records"), "vehicles", type_="foreignkey"
    )
    op.drop_index(op.f("ix_vehicles_decode_raw_record_id"), table_name="vehicles")
    op.drop_column("vehicles", "decode_raw_record_id")
    op.drop_column("vehicles", "check_digit_valid")
    op.drop_column("vehicles", "decode_error_text")
    op.drop_column("vehicles", "decode_error_code")
    op.drop_column("vehicles", "decoded_manufacturer")
    op.drop_column("vehicles", "decoded_gvwr")
    op.drop_column("vehicles", "decoded_vehicle_type")
    # ### end Alembic commands ###
